### ISSUE TITLE
can not record text input action?

### ISSUE THREAD

**Issue by prinspark** [tebelorg/TagUI#22]
I did type text twice，but no footprint remained.

click app .row:nth-child(1) .active
click app .dropdown.done:nth-child(2) .active
click app .row:nth-child(2) .text-input
click app .row:nth-child(3) .select-item.selected
click .day-name.selected .day-item
click .btn.blue-btn
click .time-picker:nth-child(1) .dropdown-toggle
click .time-picker.selected .hour:nth-child(29)
click .time-picker:nth-child(3) .default-time
click .time-picker.selected:nth-child(3) .hour:nth-child(33)
click .save-btn
click .text-area-wrapper.error.resizable textarea
click .button-inner.create-event-btn.disabled

**Comment by kensoh** [comment]
Hi @prinspark thanks for your feedback, the Chrome extension is base on [Resurrectio](https://github.com/ebrehault/resurrectio) tool and I've tested on many websites after porting over for TagUI. Can you tell more about what website are you recording and what steps are you recording?

I have just tried recording on GitHub page entering search for sikuli and it can record correctly below - 

``` 
https://github.com/tebelorg
click //a[text()="TagUI"]
click .form-control.header-search-input.js-site-search-focus.js-site-search-field.is-clearable
enter .form-control.header-search-input.js-site-search-focus.js-site-search-field.is-clearable as sikuli\r
click //a[text()="src/tagui.sikuli/tagui.py"]
```

**Comment by prinspark** [comment]
https://www.douban.com/event/create?loc=beijing,I wanna post a activity to this website.
Thanks!

**Comment by kensoh** [comment]
Oh I see.. This is a China website, when I open it asks for account in order to login. Do you have a test dummy account that I can use to take a look?

**Comment by kensoh** [comment]
We previously spoke on CasperJS issues page. If it is something not automatable by CasperJS + PhantomJS, then TagUI won't work too because TagUI uses CasperJS + PhantomJS under the hood. I'm planning to spend next couple of weeks to explore integrating TagUI with headless Chrome.

**Comment by kensoh** [comment]
Hi @prinspark have updated Chrome extension with improvements, not sure if the steps that you are trying to record is now working for you, or do you have a dummy 豆瓣 account that I can use to test?

---

Have updated Chrome extension on web store, should auto-update to users' browsers.

Packaged installations for TagUI v1.8 ([visual automation release](https://github.com/tebelorg/TagUI/releases)) also uploaded.

**Comment by kensoh** [comment]
Closing for now but do reopen if there is more info to above. Thanks for raising!
