### ISSUE TITLE
Is it work with raspberry pie 3 ?

### ISSUE THREAD

**Issue by mnlbox** [tebelorg/TagUI#23]
Hi,
Is this tool working with raspberry pie 3?
I want create a bot with it on my pie.

**Comment by kensoh** [comment]
Hi @mnlbox if you mean integrating TagUI to Raspberry Pi through REST API, there are recent updates that allow advance API calls (using different methods GET, POST, PUT etc, different headers and so on). That can integrate with a Raspberry Pi running its own REST webservice.

If you mean literally running TagUI on it, in theory that's possible but I have not tried that. Seen some articles online saying some people compile the PhantomJS binaries directly for the Raspberry. Also saw this which suggests maybe can be done without compiling.

https://quaintproject.wordpress.com/2015/04/26/how-to-install-casperjs-on-the-raspberry-pi/

The [packaged installation for Linux](https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI_Linux.zip) is running PhantomJS 64bit. You may want to try that and let me know if you have any questions? I don't have Raspberry, but your idea of running TagUI on it is very exciting! So let me know if anything I can help with.

**Comment by kensoh** [comment]
Closing the issue for now but do let me know if you have any questions or anything I can help with!
