### ISSUE TITLE
Q: How to clear field input

### ISSUE THREAD

**Issue by thim81** [tebelorg/TagUI#33]
Hi @kensoh 

I'm ashamed to ask but how can I clear a (textarea) input?
For example a basic text field input or textarea?

Currently when using textarea:

`type //textarea as Lorem ipsum`

It adds to the existing text in the textarea.

**Comment by kensoh** [comment]
Hi @thim81 this is a good question. At the moment I haven't implement that directly into TagUI. However, as TagUI uses CasperJS, you can use normal CasperJS code to do that.

```js
js this.sendKeys(tx('//textarea'), '', {reset: true});
```

The js step in front is to explicitly treat as JavaScript code, otherwise for rapid prototyping the { and } by default will be auto-parsed into nested code blocks in CasperJS syntax. Can you tell more is this a regular use case for you and usually in what situations you clear the text fields? If that is commonly used maybe I can add something into the type step, for eg `type //textarea as [clear]`.

**Comment by thim81** [comment]
Use case is typically, to **modify existing forms or data**

Examples:
- modify an account 
- modify a project name
...

**Comment by kensoh** [comment]
Thanks @thim81 it sounds like this will be better to be part of the type / enter step. Probably adding a [clear] keyword to signify emptying the field. Firefox/PhantomJS should be straightforward, Chrome need to add something more. Classifying as enhancement.

**Comment by kensoh** [comment]
Hi @thim81 I've just committed to master with following comment.

For users wanting to use this before the packaged releases are out for the next release, you can download from [master](https://git.io/vMCTZ) and overwrite your local copy (be careful if you already made local changes!)

```
Introduce [clear] keyword for step type / enter

Examples -
type element as [clear]
type email_element as [clear]test@email.com
type password_element as [clear]123456[enter]

Assumption is [clear] is always used at the start of the string to
type. Not a normal use case to type something then clear it. So TagUI
checks whether the string to type begins with [clear].
```

**Comment by siowyisheng** [comment]
this doesn't seem to be in the docs? @kensoh . I ran into this today.

**Comment by kensoh** [comment]
Yes @siowyisheng it's in the API section under type step. Can include into samples.

On this topic, there is a discrepancy between [clear] for web automation (clearing entire textbox) and [clear] when used in SikuliX eg keyboard [clear] or type abc.png as [clear]. In SikuliX, that clear only do a backspace.

You can review to see if there's value to convert that to [ctrl]a and then [del] for Windows and [cmd]a and [del] for mac to mean clearing the entire field. Not sure the combination for Linux.

**Comment by kensoh** [comment]
It wasn't straightforward and maybe to assume that the keystroke combination will clear all fields in different apps is too simplistic and not practical, so I didn't include that when the API for SikuliX was first created.
