### ISSUE TITLE
Q: Redirect issue

### ISSUE THREAD

**Issue by thim81** [tebelorg/TagUI#34]
Hi @kensoh,

We noticed strange behaviour.
We have scripts that login to gmail and then click a link, use case: account confirmation.

When clicking the link in gmail, gmail redirects should point us to the right website, but now we get to see a "blank" page only.

Any idea what could cause this?

Using debug this is what happens:
`[debug] [phantom] Navigation requested: url=https://www.google.com/url?q=https%3A%2F%2Fmandrillapp.com%2Ftrack%2Fclick%2F30863939%2Fapp.testing.loremipsum.co%3Fp%3DeyJzIjoiUDBzakwtZDBuUE82UFdENUxGQ01JQlZFWkNBIiwidiI6MSwicCI6IntcInVcIjozMDg2MzkzOSxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvYXBwLnRlc3RpbmcuaHlwZXJsYW5lLmNvXFxcL3JlZ2lzdGVyXFxcL2NvbmZpcm1cXFwvNDlkYWE0OWEtNDA4ZS00MzgzLTlkZjMtNDgxMzc2ZmFmMmQ4LTQ1NGU1OTA0LTFmNzAtNDMxZC04OTkxLTA3ZDcxNjdjYmZkNVwiLFwiaWRcIjpcIjE0NWU0NzU0YjUxNTQxNjA4YjczMjIwYWE4MjRjZTY1XCIsXCJ1cmxfaWRzXCI6W1wiZjEzY2VlNWFmMmRmYWI1YjU2ZjNhNjFkZDI0NGRkOWFkZTAxOWE1ZFwiXX0ifQ&sa=D&sntz=1&usg=AFQjCNFi4IMby8Yb_RyNG2PVmbSSb-eB-A, type=Undefined, willNavigate=true, isMainFrame=true`

**Comment by kensoh** [comment]
Hi @thim81 thanks for giving this scenario. I've heard of issues with redirection with PhantomJS, in some situations due to lack of real-browser headers, in some situations something may be broken. Does the issue happen for you when running in visible or headless Chrome mode?

**Comment by kensoh** [comment]
Adding on for reference a solved issue with redirection in CasperJS - https://github.com/casperjs/casperjs/issues/1600
And PhantomJS making some new commits regarding redirects - https://github.com/ariya/phantomjs/pull/15044

**Comment by thim81** [comment]
Since CasperJS is not supported on Chrome, I run the tests with Firefox in the visible mode.

**Comment by thim81** [comment]
For now there is no way around the gmail redirect?

**Comment by kensoh** [comment]
How do you replicate the issue? Is it you run in normal mode, let it login on the PhantomJS browser, then click on any external URL link in an email?

**Comment by thim81** [comment]
@kensoh 

I'm affraid that it most be something very specific.
We are doing a work-a-round by using a temporary mail confirmation flow by using a service like mailinator instead of Gmail. That way there is no redirect issue anymore.

**Comment by thim81** [comment]
@kensoh 

Using a alternative mail service, also causes a redirect, so it's not really clear how to resolve this in the flow?

I checked the references but I'm not sure what to do with the references? They remain open or can I do something like in my flow?

`
casper.start('http://tebel.org', function() {
this.echo(this.getCurrentUrl());})

casper.thenOpen('http://tebel.org/a.html', function() {
this.echo(this.getCurrentUrl());})

`

**Comment by thim81** [comment]
Not sure if this is related but it seems so.

Perhaps the issue is that it always opens a blank window which is actually blank

**Comment by thim81** [comment]
Update: when running the flow on Chrome.

It blocks the opening of the page because it considers it a popup.

After allowing the popup in chrome, the window opens just fine on Chrome.

Perhaps this is the reason also for Firefox? That the popup gets blocked.

**Comment by kensoh** [comment]
Thanks for reopening this @thim81 I see, I have experience with running on Firefox when some popup or new window opens. Until now I am not sure why. TagUI uses CasperJS which uses SlimerJS which runs a wrapper around the Gecko engine.

I have experimented in the past dealing with cookies by specifying the profile but it is really hard to make any progress, even with specifying profile there is Firefox window that requires user manually selecting and can't run automatically.

There is a recent related issue at SlimerJS repo - https://github.com/laurentj/slimerjs/issues/622. If you disable popup-blocking option in preferences is it able to help?

**Comment by thim81** [comment]
No such luck for now, because I checked the popup blocking settings and they all seems.

I'm using MacOS Firefox 54.0.1 (64-bit)

**Comment by kensoh** [comment]
I see.. thanks @thim81 I've raised an issue at SlimerJS (the project that drives Firefox). CasperJS will talk to SlimerJS to control Firefox. You may want to subscribe to that issue so that you can get updates.

As the generated CasperJS code is correct and works for PhantomJS/Chrome, I'll close this issue for now as it seems to be some issue in the CasperJS->SlimerJS->Firefox chain.

https://github.com/laurentj/slimerjs/issues/636
