### ISSUE TITLE
BUG - Chrome crash

### ISSUE THREAD

**Issue by thim81** [tebelorg/TagUI#35]
On Chrome, we have run into the following issue regularly.
I have no idea why or what could cause this.

```
PHP Fatal error:  Uncaught exception 'WebSocket\ConnectionException' with message 'Empty read; connection dead?  Stream state: {"timed_out":true,"blocked":true,"eof":false,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false}' in /Users/tim/Sites/localhost/tagui/src/ws/Base.php:269
Stack trace:
#0 /Users/tim/Sites/localhost/tagui/src/ws/Base.php(143): WebSocket\Base->read(2)
#1 /Users/tim/Sites/localhost/tagui/src/ws/Base.php(135): WebSocket\Base->receive_fragment()
#2 /Users/tim/Sites/localhost/tagui/src/tagui_chrome.php(47): WebSocket\Base->receive()
#3 {main}
  thrown in /Users/tim/Sites/localhost/tagui/src/ws/Base.php on line 269
```

**Comment by kensoh** [comment]
Thanks @thim81, do you have examples of simple scripts that can consistently replicate this issue? I have tried running scenarios with over 10k transactions at a go without issue. It sounds like some communication issue for some situations broken between the websocket-php and Chrome.

**Comment by thim81** [comment]
@kensoh 

It happens when trying to take "snap"

Example flow that causes a crash on my Mac system.

```
http://tebel.org/gist/about_tebel

snap page to 2-1-sign_up.png
```

**Comment by kensoh** [comment]
That's interesting and useful datapoint.. It works on my macOS. I'm running 10.12.6 (2014 macbook air). That page is JavaScript/image heavy. I added a wait before snapping the page to make sure the parallax image is rendered. What are your environment like? Is it part of npm install tagui or a separate folder from the unzipped packaged installation?

```
http://tebel.org/gist/about_tebel
wait
snap page to 2-1-sign_up.png
```

![2-1-sign_up](https://user-images.githubusercontent.com/10379601/28676847-61d77e6e-731e-11e7-9349-b22c0ad3d034.png)

**Comment by kensoh** [comment]
Adding on troubleshooting note for reference - I was running Chrome 59.0.3071.115 (Official Build) (64-bit), after updating to  60.0.3112.78 (Official Build) (64-bit) both work for me in headless/visible mode.

**Comment by thim81** [comment]
I'm running macOS 10.11.6 on a MacBook Pro with a Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by thim81** [comment]
By adding the wait 3.0 before the snap, the error seems to have disappeared.

**Comment by kensoh** [comment]
This is really tricky, I really want to nail down this type of sporadic hard to replicate issues.

TagUI only starts execution after the websocket connection from Chrome is ready for link-up. From the error message, it looks like can happen in a scenario where Chrome isn't ready to send but TagUI asks for response. In any case, do let me know if you encounter some scenario where this can be replicated, I'm really keen to hunt down this. Thanks @thim81 !

**Comment by kensoh** [comment]
Encountered this error, which happens sometimes when a response is expected from Chrome (after a websocket send) but there is nothing received. Handled the exception by looping until a response from Chrome is received. Made above commit with the following comments. Hope this fixes the issue!

---

Sometimes, a read expecting message response from Chrome does not get a response. this will throw error and hang the automation. this commit handles such exception by looping until a response from Chrome is received.
