### ISSUE TITLE
Bug - frame msg_body

### ISSUE THREAD

**Issue by thim81** [tebelorg/TagUI#38]
Hi @kensoh 

I run into a bug when trying to use the `frame` method in a test flow

`./src/tagui ./sample/2_signup_user firefox test`

In this flow we use Mailinator to confirm a mail.
When opening the mail, it opens the mail in a an iframe.

when using `frame msg_body` in the flow

`tagui $ ./src/tagui ./sample/2_signup_user firefox test`

It just outputs 

`Test file: /Users/Sites/localhost/tagui/sample/2_signup_user.js      `

And then just wait.

If we comment out `frame msg_body` in the flow, it runs the test without any problems, but it cannot click on anything the iframe

`./src/tagui ./sample/2_signup_user firefox test`

```
Test file: /Users/Sites/localhost/tagui/sample/2_signup_user.js           
Mon Jul 31 2017 14:00:35 GMT+0200 (CEST) 
# /Users/Sites/localhost/tagui/sample/2_signup_user 
# https://app.testing.co/login - testing 
# click Create your free account 
...
```

**Comment by thim81** [comment]
Here is the source code of the page with the iframe



  |  
-- | --
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <html lang="en" id='ng-app' ng-app class='ng-app'>
  | <head>
  | <meta charset="utf-8">
  | <title>Mailinator</title>
  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
  | <meta name="keywords" content="email, mail, disposable mail, mailinator, qa testing, quality assurance, testing"/>
  | <meta name="description" content="Mailinator - Any Inbox. Any Time."/>
  | <link rel="shortcut icon" href="/ico/favicon.ico">
  | <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" rel="stylesheet">
  |  
  | <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  |  
  | <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700" rel="stylesheet">
  | <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet">
  | <link href="/css/style-library-1.css" rel="stylesheet">
  | <link href="/css/plugins.css" rel="stylesheet">
  | <link href="/css/blocks.css" rel="stylesheet">
  | <link href="/css/custom.css" rel="stylesheet">
  | <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  | <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  |  
  | 
  | 
  |  
  | <script src="/js/html-css-sanitizer-minified.js"></script>
  |  
  | </head>
  |  
  | <head>
  | <title>Mailinator</title>
  | <meta charset="UTF-8"/>
  | <meta name="keywords" content=""/>
  | <meta name="description" content=""/>
  | <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  | <link href="css/reset.css" rel="stylesheet"/>
  | <link rel="stylesheet" href="css/selectric.css"/>
  | <link href="css/layout.css" rel="stylesheet"/>
  | <link href="css/mobile.css" rel="stylesheet"/>
  | <link href="../css/font-awesome.min.css" rel="stylesheet">
  |  
  | <script src="/manyauth/js/manyauthutils.js"></script>
  |  
  | </head>
  | <body data-spy="scroll" data-target="nav"
  | style="font-family:'Lato', 'Helvetica Neue', Helvetica, Arial, sans-serif" ng-controller="InboxCtrl"
  | id="InboxCtrl">
  |  
  |  
  |  
  |  
  | <header id="header">
  | <div class="container">
  | <div class="header_left_logo" style="float:left;margin: 0;padding: 0;height:100%;background-color: #183442">
  | <img src="images/icons/-delete.svg" class="corss-img"/>
  | <img src="images/icons/menu.svg" class="burger-img"/>
  |  
  | <a href="/" class="header_logo">
  | <img src="../img/mailinatorguy.png" class="header_logo-img"/>
  | </a>
  |  
  | <div class="header_logo_text" style="cursor:pointer;float:left;font-weight: bold;color:white;"
  | onclick="window.location='/'">
  | MAILINATOR
  | </div>
  | </div>
  |  
  | <div class="login_tag" style="border:1px solid #c1c1c1;">
  | <a href="/manyauth/signup.jsp" class="hader_menu-link">Sign up</a>
  | </div>
  | <div class="login_tag">
  | <a href="/manyauth/login.jsp" class="hader_menu-link">Log in</a>
  | </div>
  | <div class="login_tag">
  | <span class="dropdown" >
  | <i class="fa fa-smile-o fa-lg dropbtn" onclick="otherMenuClick();" style="color:#eee;"></i>
  | <span class="dropdown-content" id="other_menu" style="text-align: left;">
  | <a href="/pricingmatrix.jsp">Upgrade</a>
  | <a href="/faq.jsp">FAQ</a>
  | <a href="/apidocs.jsp">API</a>
  | </span>
  | </span>
  | </div>
  |  
  | </div>
  | <div class="lb_search_full" id="mobile_search">
  | <input type="text" placeholder="Enter Inbox" class="lb-input"
  | onkeydown="if (event.keyCode == 13) { subInboxSameZone($('#inbox_field_mob').val()); $('#inbox_field_mob').blur(); return false; }"
  | id="inbox_field_mob"/>
  | <span id='inbox_button_mob' class="lb-btn"
  | onclick="subInboxSameZone($('#inbox_field_mob').val());  $('#inbox_field_mob').blur(); return false;">
  | <i class="fa fa-envelope fa-2x" style="color:white;padding-top: 8px;"></i>
  | </span>
  | </div>
  | <div class="mail_header-all2" id="status_bar">
  | <div id="activity_light" style="float:left;padding-top: 8px;"
  | title="Mailinator Stream Connection Status">
  | <i class="fa fa-circle fa-lg" style="color:#444;" id="act_light"></i>
  | </div>
  | <div id="pause_icon"
  | onclick="userPauseStream()"
  | style="float:left;margin-left: 5px;padding-top: 8px;" title="Pause incoming emails">
  | <i class="fa fa-pause fa-lg" style="color:#aaa" id="play_button"></i>
  | </div>
  | <div style="float:left;padding-top: 5px;" id="query_data">
  | <div class="header-controls_desc1" style="margin-left: 1.5em;">
  | privacy-level:
  | </div>
  | <div class="header-controls_desc2">
  | {{visibility}}
  | </div>
  | <div class="header-controls_desc1" style="margin-left: 2rem;">
  | query:
  | </div>
  | <div class="header-controls_desc2" title="This Inbox receives all email sent to this address">
  | {{original_query}}
  | </div>
  | </div>
  | <div id="pin_inbox_icon"
  | onclick="pinInbox();"
  | style="float:left;margin-left: 3px;padding-top:5px;cursor: pointer;display: {{save_eligible}}"
  | title="Save this Query">
  | <i class="fa fa-plus-square fa-lg1" style="color:#2472a4;padding-left:2px;"></i>
  | </div>
  |  
  | <div style="float:right" style="margin:0;padding:0;">
  | <span id="pane_status_msg" class="pane_status" style="color:blue;"></span>
  | <span id="pane_error_msg" class="pane_status" style="color:red;"></span>
  | <span class="fa-stack fa-manylarge" title="Delete Emails"
  | onclick="trashEmails();"
  | style="cursor: pointer">
  | <i class="fa fa-square fa-stack-2x" style="color:#aaa" id="trash_but"></i>
  | <i class="fa fa-trash fa-stack-1x fa-inverse"></i>
  | </span>
  | <span class="fa-stack fa-manylarge"
  |  
  | title="Login to Save Emails"
  |  
  | style="cursor: pointer">
  | <i class="fa fa-square fa-stack-2x" style="color: #aaa" id="save_but"></i>
  | <i class="fa fa-save fa-stack-1x fa-inverse"></i>
  | </span>
  | <span class="fa-stack fa-manylarge"
  |  
  | title="Login to Forward Emails"
  |  
  | style="cursor: pointer;">
  | <i class="fa fa-square fa-stack-2x" style="color: #aaa" id="forward_but"></i>
  | <i class="fa fa-mail-forward fa-stack-1x fa-inverse"></i>
  | </span>
  | </div>
  |  
  | </div>
  | </header>
  |  
  |  
  | <script type="text/javascript">
  | function updateLinks(tree) {
  |  
  | tree.find('a').each(function () {
  | var href = $(this).attr('href');
  | if (href && href.length > 0) {
  | if (href.indexOf('mailinator') > 0 \|\| href.indexOf("clickrouter") > 0 \|\| href == "/" \|\|
  | href.indexOf("stripe") > 0) {
  |  
  | } else {
  | //console.log(href);
  | href = escape(href);
  | href = "http://click1.clickrouter.com/redirect?token=a2258079c24c4c50a56b6b1ffb75d6e2&" +
  | "url=" + href;
  | $(this).attr('href', href);
  | }
  | }
  | });
  |  
  | }
  |  
  | var manyuser = false;
  |  
  | var muValidated = false;
  |  
  |  
  |  
  |  
  | var manyteam = false;
  |  
  |  
  | </script>
  |  
  | </header>
  | <section class="lb lb_all" style='background: #eee;position:fixed;'>
  | <div class="lb-container">
  | <div class="lb-container-text">
  |  
  | <div class="lb-search">
  | <input type="text" placeholder="Enter Inbox" class="lb-input"
  | onkeydown="if (event.keyCode == 13) { subInboxSameZone($('#inbox_field').val()); return false; }"
  | id="inbox_field"
  | />
  | <span id='inbox_button' class="lb-btn"
  | onclick="subInboxSameZone($('#inbox_field').val()); return false;">
  | <i class="fa fa-envelope fa-2x" style="color:white;padding-top: 8px;"></i>
  | </span>
  | </div>
  | </div>
  |  
  | <div class="lb_all_list">
  |  
  |  
  | <ul>
  | <li ng-repeat="status in status_list"
  | class="lb_all_item">
  | <p class="lb_all-text {{status.active}}" id='bigrow_{{status.status_zone}}'
  | onclick="itemInboxClick('{{status.status_zone}}')">
  | {{status.title}}<span>{{status.count}}</span></p>
  | <ul class="lb_all_sub-list">
  | <li ng-repeat="query in status.query_list"
  | class="lb_all_sub-item {{query.active}}"
  | onclick="subItemInboxClick('{{query.zone}}', '{{query.text}}')">
  | <div class="lb_all_sub-item_text">
  | {{query.pretty}}
  | <div style="min-width: 2.4rem;float:right;text-align: right;"
  | onclick="unpinInbox('{{query.zone}}', '{{query.text}}', '{{query.saved}}');if(event.stopPropagation){event.stopPropagation();}event.cancelBubble=true;"
  | title="Delete Saved Query">
  | <i class="fa fa-close"
  | style="display:{{query.saved}};cursor: pointer;margin-left: 3px;color:#aaa;"></i>
  | &nbsp;
  | </div>
  | <div style="float:right">
  | {{query.count}}
  | </div>
  | </div>
  | </p>
  | </li>
  | </ul>
  | </li>
  | </ul>
  |  
  | </div>
  |  
  |  
  | <br>
  | <br>
  | <br>
  |  
  | <div style="margin: 10px 0 20px 0;text-align: center;font-size: 16px;display: none;" id="ad_clickrouter1">
  | Mailinator Blog:<br>
  | <a href="https://mailinator.blogspot.com/2017/07/introducing-mailinator-real-time-inbox.html"><strong>Introducing the Mailinator Realtime Inbox !</strong></a>
  | </div>
  |  
  | <div style="margin: 10px 0 20px 0;text-align: center;font-size: 16px;display: none;" id="ad_clickrouter2">
  | Need your own Private Mailinator?
  | <a href="/pricingmatrix.jsp">Upgrade Now</a>
  | </div>
  |  
  | <div style="text-align:center;margin:0;padding:0;display: none;" id="googad">
  | <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  | 
  | <ins class="adsbygoogle"
  | style="display:inline-block;width:160px;height:600px"
  | data-ad-client="ca-pub-8366735459736268"
  | data-ad-slot="8480074758"></ins>
  | <script>
  | (adsbygoogle = window.adsbygoogle \|\| []).push({});
  | </script>
  | </div>
  |  
  | <div style="margin: 10px 0 20px 0;text-align: center;display:none" id="ad_clickrouter">
  | Links monetized by <a href="https://www.clickrouter.com">ClickRouter</a>
  | </div>
  |  
  |  
  |  
  |  
  | </div>
  | </section>
  | <main class="index all-message-index">
  | <section class="single_mail">
  | <div id="msgpane" class="msg" style="display: none;">
  | <div>
  | <div style="font-size:2rem;float:left;width: 75%;">
  | {{msg.subject}}
  | </div>
  | <div style="font-size:1.1rem;float:right;text-align:right;width:5%">
  | &nbsp;
  | </div>
  | <div style="font-size:1.1rem;float:right;text-align:right;width:20%">
  | {{msg.received}}
  | &nbsp;
  | &nbsp;
  | &nbsp;
  | &nbsp;
  | <span style="float:right;width:8%;font-size:1.1rem;" id="contenttypebuttons">
  | </span>
  | </div>
  | </div>
  | <div style="clear: both;margin-top: 33px;">
  | <hr>
  | </div>
  |  
  | <iframe id="msg_body" style="border: 0;overflow: hidden;"
  | width="100%"
  | height="100%"
  | name="msg_body" marginheight="0">
  | EMAIL BODY
  | </iframe>
  |  
  | </div>
  | <div id='publicm8rguy'
  | style="display:none;text-align:center;background-color:#fff;font-size:18px;padding-top: 40px;">
  | <br>
  | <br>
  | [ This Inbox channel is currently Empty ]
  | <br>
  | <br>
  | <img src="/assets/img/mailinatorguy.png">
  | </div>
  |  
  | <ul class="single_mail-body" id="inboxpane">
  | <li class="all_message-item all_message-item-parent cf"
  | ng-repeat="email in emails" id="row_{{email.id}}"
  |  
  | onclick="showTheMessage('{{email.id}}');">
  |  
  | <div class="all_message-min">
  | <div class="all_message-min-check-container"
  | id='check_{{email.id}}'
  | onclick="checkBox('{{email.id}}');if(event.stopPropagation){event.stopPropagation();}event.cancelBubble=true;">
  | <i class="fa fa-check-square fa-lg" style="display:none;color#aaa;"
  | id="checkon_{{email.id}}"></i>
  | <i class="fa fa-square-o fa-lg" style="color:#aaa;" id="checkoff_{{email.id}}"></i>
  | </div>
  | <div class="all_message-min_autor" style="display:{{email.to ? 'block':'none'}}" title="TO">
  | {{email.to}}
  | </div>
  | <div class="all_message-min_autor" title="FROM">{{email.from}}</div>
  | <div class="all_message-min_text {{email.to?'':'all_message-min_text-3'}}">{{email.subject}}</div>
  | <div class="all_message-min_datte all_message-min_datte-3">{{email.humandate}}</div>
  | </div>
  | </li>
  | </ul>
  | <div style="height:80px;background-color: #ffffff"></div>
  |  
  | </section>
  | </main>
  |  
  | <script src="js/jquery.selectric.js"></script>
  | <script src="js/script.js"></script>
  |  
  | <script src="../js/angular.min.js"></script>
  |  
  | <script type="text/javascript" src='../assets/js/jquery.timeago.js'></script>
  | <script type="text/javascript" src='../assets/js/jquery.address.js'></script>
  | <script type="text/javascript" src="js/m8r.js?887"></script>
  |  
  | <footer id="footer">
  | <div style="float:left;padding:15px 15px 0 15px;">
  | <a href="/pricingmatrix.jsp" style="cursor: pointer;">
  | PRICING
  | </a>
  | </div>
  | <div style="float:left;padding:15px 15px 0 15px;">
  | <a href="/faq.jsp" style="cursor: pointer;">
  | FAQ
  | </a>
  | </div>
  | <div style="float:left;padding:15px 15px 0 15px;">
  | <a href="/apidocs.jsp" style="cursor: pointer;">
  | API DOCS
  | </a>
  | </div>
  | <div style="float:left;padding:15px 15px 0 15px;">
  | <a href="https://mailinator.blogspot.com" rel=nofollow style="cursor: pointer;">
  | BLOG
  | </a>
  | </div>
  | <div class="right_foo">
  | <p class="copyright-text">Copyright 2017 Manybrain, Inc. All Right Reserved. <a href="/terms.jsp">Terms and
  | Conditions</a> and <a href="/terms.jsp">Privacy Policy</a>
  | &nbsp;
  | &nbsp;
  | &nbsp;
  | <a href="/cdn-cgi/l/email-protection#6c1f191c1c031e182c010d02150e1e0d0502420f0301"><i class="fa fa-envelope">&nbsp;&nbsp;<span class="__cf_email__" data-cfemail="6e1d1b1e1e011c1a2e030f00170c1c0f0700400d0103">[email&#160;protected]</span><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript\|\|function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)\|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></i></a>
  | </p>
  | </div>
  | </footer>
  | <script type="text/javascript">
  | /* When the user clicks on the button,
  | toggle between hiding and showing the dropdown content */
  | function gearClick() {
  | document.getElementById("myDropdown").classList.toggle("show");
  | }
  |  
  | function otherMenuClick() {
  | document.getElementById("other_menu").classList.toggle("show");
  | }
  |  
  | // Close the dropdown menu if the user clicks outside of it
  | window.onclick = function (event) {
  | if (!event.target.matches('.dropbtn')) {
  |  
  | var dropdowns = document.getElementsByClassName("dropdown-content");
  | var i;
  | for (i = 0; i < dropdowns.length; i++) {
  | var openDropdown = dropdowns[i];
  | if (openDropdown.classList.contains('show')) {
  | openDropdown.classList.remove('show');
  | }
  | }
  | }
  | }
  | </script>
  | <script>
  | (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]\|\|function(){
  | (i[r].q=i[r].q\|\|[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  | m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  | })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  |  
  | ga('create', 'UA-170806-1', 'mailinator.com');
  | ga('send', 'pageview');
  |  
  | </script>
  |  
  |  
  | <script type="text/javascript">
  | adroll_adv_id = "VMN4XCGWCNE5PPIHTM52HX";
  | adroll_pix_id = "AYN7TMHAPFAS5BJF723VO2";
  | (function () {
  | var oldonload = window.onload;
  | window.onload = function(){
  | __adroll_loaded=true;
  | var scr = document.createElement("script");
  | var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
  | scr.setAttribute('async', 'true');
  | scr.type = "text/javascript";
  | scr.src = host + "/j/roundtrip.js";
  | ((document.getElementsByTagName('head') \|\| [null])[0] \|\|
  | document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
  | if(oldonload){oldonload()}};
  | }());
  | </script>
  |  
  |  
  |  
  | <script>/* <![CDATA[ */(function(d,s,a,i,j,r,l,m,t){try{l=d.getElementsByTagName('a');t=d.createElement('textarea');for(i=0;l.length-i;i++){try{a=l[i].href;s=a.indexOf('/cdn-cgi/l/email-protection');m=a.length;if(a&&s>-1&&m>28){j=28+s;s='';if(j<m){r='0x'+a.substr(j,2)\|0;for(j+=2;j<m&&a.charAt(j)!='X';j+=2)s+='%'+('0'+('0x'+a.substr(j,2)^r).toString(16)).slice(-2);j++;s=decodeURIComponent(s)+a.substr(j,m-j)}t.innerHTML=s.replace(/</g,'&lt;').replace(/\>/g,'&gt;');l[i].href='mailto:'+t.value}}catch(e){}}}catch(e){}})(document);/* ]]> */</script></body>
  | </html>
  |

**Comment by kensoh** [comment]
Hi @thim81 thanks for reporting this! If there is no sensitive info, can you paste the section of the generated CasperJS .js code around the frame handling here?

It sounds like the generated CasperJS code is likely to be ok, otherwise there will be runtime JS error. The name of the frame also exists in the HTML DOM.

But somehow the interaction broke somewhere along TagUI-CasperJS-SlimerJS-Firefox. Also, if you run using default mode (PhantomJS) without firefox option, and run with chrome option to run through Chrome, does the same error of hanging there happen? This info can help to isolate where is the cause of the execution hanging.

**Comment by thim81** [comment]
Here is the flow

```
http://www.mailinator.com/v2/inbox.jsp?zone=public

// = MOCKING ========================================================= //

// Mocking data
data_test = "hyper.koopa.bowser"; 

// = Mailinator ================================================================= //
https://www.mailinator.com/v2/inbox.jsp?zone=public
wait 3.0

click inbox_field
enter inbox_field as '+data_test+'
click #inbox_button

// Show success
wait 3.0

// Click register mail
test.assertSelectorHasText(tx('body'), 'Register','Check if mail is send properly to '+data_email+'');
click Register
wait 3.0

// Click confirmation link
// JS this.page.switchToChildFrame(0); // this works but the causes the blank popup behaviour
frame msg_body

click Confirm email address // causes blank popup
wait 6.0

```

**Comment by kensoh** [comment]
Running the flow with default option works. The generated .js code for frame handling is below and looks ok.

```js
casper.wait(3000, function() {
// Click confirmation link
// JS this.page.switchToChildFrame(0); // this works but the causes the blank popup behaviour
{techo('frame msg_body');
casper.withFrame('msg_body', function() {
{techo('click Confirm email address // causes blank popup');
casper.waitFor(function check() {return check_tx('Confirm email address // causes blank popup');},
function then() {this.click(tx('Confirm email address // causes blank popup'));},
function timeout() {this.echo('ERROR - cannot find Confirm email address // causes blank popup').exit();});} });} });
```

Below is the automation result. Note that the // comment after click Confirm email address should be removed as TagUI will literally take it as part of the text string to look out for -
```
START - automation started - Tue Aug 01 2017 00:53:54 GMT+0800 (+08)
http://www.mailinator.com/v2/inbox.jsp?zone=public - Mailinator

wait 3.0
click inbox_field
enter inbox_field as hyper.koopa.bowser
click #inbox_button
wait 3.0
click Register
wait 3.0
frame msg_body
click Confirm email address
wait 6.0

http://www.mailinator.com/v2/inbox.jsp?zone=public#/#msgpane - Mailinator
FINISH - automation finished - 24.9s
```

Running with Firefox options works for me as well until the part where the popup appears. Running with chrome without test option also works. Looks like there is difference is execution behavior between your system and mine. I'm running on macOS v10.12.6 and Firefox v53.0.2 (64-bit).

You haven't share your chrome or default mode result, and I assume when you say it just wait means hang without any error message. It should throw error after default 10s timeout, even if the click has the extra // comment behind, and not just wait there.

**Comment by thim81** [comment]
Indeed it works properly.

Must be something else in my flow that causes the stopping.
