### ISSUE TITLE
Q: API - header parameters

### ISSUE THREAD

**Issue by thim81** [tebelorg/TagUI#39]
Is it possible to set specific header parameters for the `API` method?
For example for using API keys or token or basic auth.

Or is it beter to use a NodeJS framework in the flow for more advanced API calls?

**Comment by kensoh** [comment]
Hi @thim81 yes API headers in `api_config` variable before calling api step. The API section of the developers section has some examples on this. Let me know if you run into something!

https://github.com/tebelorg/TagUI#api

**Comment by thim81** [comment]
somehow I must have missed this, I'll give it try tomorrow
