### ISSUE TITLE
DOC - Correction in sample

### ISSUE THREAD

**Issue by thim81** [tebelorg/TagUI#40]
I noticed a very small mistake in your sample

https://github.com/tebelorg/TagUI/blob/master/src/samples/3_github

> echo 'Country name - ' + api_json.RestResponse.result.name

should be

> echo 'Country name - ' + api_result.RestResponse.result.name

**Comment by thim81** [comment]
My bad, it works as expected.

**Comment by kensoh** [comment]
Oh yep, api_result is the raw text string returned by the API call. api_json is a JSON object that will be created, if the response from webservice is in JSON format. If not, api_json will be null.
