### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lakinmohapatra** [tebelorg/TagUI#45]
I used this tool for testing my web.
It was so helpful for me .
Even a normal php developer having no knowledge in automation can use it . 

Keep up good work guys .

**Comment by kensoh** [comment]
Hi @lakinmohapatra thanks for your feedback! You're welcome.

Also want to share with you a list of some new tools for test automation with headless Chrome - 
https://medium.com/@kensoh/chromeless-chrominator-chromy-navalia-lambdium-ghostjs-autogcd-ef34bcd26907

I've also updated that list to the awesome test automation list (not affiliated with them) but find that list very useful to keep track of various testing tools. They also have a list for PHP tools there :smile:
https://github.com/atinfo/awesome-test-automation

**Comment by kensoh** [comment]
Closing the issue for now, thanks for your feedback @lakinmohapatra !
