### ISSUE TITLE
Need usage example docs 

### ISSUE THREAD

**Issue by lakinmohapatra** [tebelorg/TagUI#46]
We need some examples on how to use conditionals .

**Comment by kensoh** [comment]
Hi @lakinmohapatra yes there is an example 4 on the use of conditions, in the flow samples section of readme - https://github.com/tebelorg/TagUI#flow-samples

This is the direct link to that sample - (I think it will fail at facebook step, now facebook ask for captcha)
https://github.com/tebelorg/TagUI/blob/master/src/samples/4_conditions

You can type conditions in JavaScript or in natural language. Eg, both examples below can be used - 

```
read some_price_element to item_price
if item_price greater than 21
echo "Price is too expensive - $" item_price
```
```
read some_price_element to item_price
if (item_price > 21)
echo "Price is too expensive - $" item_price
```

In the readme there is also a section with more examples of different conditions -
https://github.com/tebelorg/TagUI#conditions-examples

**Comment by lakinmohapatra** [comment]
Thanks for your response. 
If we will be using javascript directly , do we need to use any js step ? 
Please let me know.

**Comment by kensoh** [comment]
In most cases, there is no need to use js step, as TagUI automatically checks and recognize commonly used JavaScript code. But if TagUI shows an error message for something you are trying to do in JS, you can use js step followed by the JS statement to force it as JavaScript code.

Actually TagUI can be designed in a simpler way to assume anything that is not official steps to be JS code. But I intentionally make it do this checking to try to feedback error in the script before the automation even starts. I find a lot of time can be wasted if we only see the errors during execution. Better to fix whatever is possible before even running.

**Comment by kensoh** [comment]
Closing for now, but do reopen if you run into anything.

Wish you have fun using the tool for web automation!
