### ISSUE TITLE
Conditional logic?

### ISSUE THREAD

**Issue by sirwlm** [tebelorg/TagUI#47]
Are there any plans (or have I somehow missed) conditional logic with tagui?

What I mean is, lets say I need to check if something has changed on a website, and if it has changed, do some other actions, for example log in and take a screenshot, but I only want that to happen if an object is found on the loaded page, otherwise it can just discard it and move onto the next website. I'm sure there has to be a way to do this with tagui I'm just overlooking it.

**Comment by sirwlm** [comment]
Wow, can't believe I didn't look at the cheat sheet first. Closing the issue, sorry!

**Comment by kensoh** [comment]
@sirwlm thanks for asking this interesting question! Yes the cheat sheet covers on conditions, but I think I missed out something in the readme. TagUI actually has a `check_tx()` function to check for existence of a web element. Somehow I didn't put it in readme and abstracted that part away, thinking most use cases won't be interested to check manually if something exists.

By default, TagUI will auto-wait and check, then time-out if element hasn't appear by then. In any case, what you are looking for is something like below. You can use `check_tx()` function followed by the element string to return true or false if something is there. This should be added to readme, hmm..

```
http://tebel.org/index_mobile.php
if check_tx('footer')
echo 'footer present'
else
echo 'footer missing'
```

**Comment by kensoh** [comment]
Added a tip in conditions examples for check_tx()
this can be useful for some conditional use cases -
https://github.com/tebelorg/TagUI#conditions-examples
