### ISSUE TITLE
How can install CLI command via npm ?

### ISSUE THREAD

**Issue by Leko** [tebelorg/TagUI#50]
Hi there.
I want to install TagUI via `npm install` but I can't execute `tagui` command.
Because `bin` is not specified in package.json.

I think there is simple.
Just add `"bin":"src/tagui"` to package.json.

How do you think ?

**Comment by kensoh** [comment]
Thanks @Leko ! Committed with following comment and published to npm - 

- originally want users to symlink on their own (tip in To Use section)
- but for npm this should be the best practice to symlink automatically
- not sure if it will work for windows as windows runner is tagui.cmd
- in any case it’s similar to casperjs, can roll-back later if there’s issue

I can't test as I already have local symlinks, but do shout out if it doesn't work for you!

Also, I'm using ./ in front for best practice `"bin": "./src/tagui",`

**Comment by Leko** [comment]
Thank you for immediate response.
I try to install again. It works fine !

> in any case it’s similar to casperjs, can roll-back later if there’s issue

I got it. I'll keep that in mind.
Please close this issue.

**Comment by kensoh** [comment]
Cool, thanks @Leko for suggesting this improvement!
