### ISSUE TITLE
multiple tests

### ISSUE THREAD

**Issue by armthehomeless2112** [tebelorg/TagUI#52]
I was wondering if there is a clean way of iterating through multiple pages? I need to preform the same function across 130+ pages. I also the previous issue where you wrote a bash script to automate multiple test, but I thought there might an easier than write the same code with different url's and looping through with a script. My js isn't the best so if it's something really basic, i apologize.

**Comment by kensoh** [comment]
Hi @armthehomeless2112 can you share more what type of pages and type of actions you are doing when looping through?

Usually, you can use csv file to run the same automation flow with different data sets. More details in [datatables section](https://github.com/tebelorg/TagUI#datatables). TagUI supports both the traditional way of listing records and the data-centric way, below is a sample - 

**flowfile**
```
`url_to_visit`
snap page
```

save csv as **flowfile.csv** (data-centric format)

datatable|1|2|3
:--------|:---|:---|:---
url_to_visit | http://test1.com | http://test2.com | http://test3.com

OR 

save csv as **flowfile_transpose.csv** (traditional format)

datatable|url_to_visit
:--------|:----------
1|http://test1.com
2|http://test2.com
3|http://test3.com

**Comment by armthehomeless2112** [comment]
Without going into too much detail, I am going through a reset process so currently the flow looks like this

http://'+loginSite+''+port+'
click reset.html
click factory
http://'+loginSite2+''+port+'
click reset.html
click tr:nth-child() input
wait 
http://'+loginSite+''+port+'

the ports are non-sequential and really thats the only thing other than the flow that needs to be looped through. But making it into a csv makes sense. I definitely overlooked that. Thanks for the help

**Comment by kensoh** [comment]
I see.. If the website you are accessing does not require login with userid and password, that should be ok. If it requires login then maybe run in chrome mode or something, otherwise the large number of repetitions will spam the website with repeated login and logout requests.
