### ISSUE TITLE
Issue with backslashes (and possibly other characters) in strings

### ISSUE THREAD

**Issue by ccman32** [tebelorg/TagUI#54]
Hello,

I noticed that when using strings that contain backslashes in a script, those backslashes seem to get escaped and I don't know how to prevent that. I created a simple script that logs in on a website but whenever the password of the account that is used for logging in contains backslashes the script won't work unless I manually replace all backslashes in the password with two backslashes. How can I ensure that exactly the string which is written in the script will be used as the password?

**Comment by kensoh** [comment]
Hi @ccman32  looks like have to be handled at the source data by providing inputs to have \\\\ whenever there is \\. As TagUI underlying execution environmental is JavaScript, the \ character in strings will be [treated as escape character](https://stackoverflow.com/questions/3903488/javascript-backslash-in-variables-is-causing-an-error). Below more notes for inputs / reference.

If your password input is manually entered, it can be done by what you said, putting \\\\. If it is from command line input or from csv datatable, I tried something like below but it's not possible to get the original unescaped string. Once a string is created \\n is interpreted by JavaScript into line break. 

**command line input**
```
https://github.com/tebelorg
text = p1
text = text.replace(/\\/g,'\\\\')
echo text
enter q as '+text+'
snap page
```

**csv datatable**
```
https://github.com/tebelorg
text = "`password`"
text = text.replace(/\\/g,'\\\\')
echo text
enter q as '+text+'
snap page
```

In theory, can make a function to replace line breaks and other escaped conversions back into strings. Or even intercept that during reading from datatable. But that will break other valid use cases such as enter text input with line breaks in textarea field. The [String.raw()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw) in newer JavaScript may not be compatible with the underlying PhantomJS engine, even if it does, the \`\` syntax also conflicts with the datatable syntax for TagUI.

**Comment by kensoh** [comment]
If really can't get the input containing \\ to be \\\\ you can consider trying something like below. It may work for csv datatables but it is unreliable way. Will eventually fail on some data. It tries to search and replace a list of [escape sequences](https://mathiasbynens.be/notes/javascript-escapes). \\b is left out, it appears even when there isn't \\b.

```
https://github.com/tebelorg
text = "`password`"
text = text.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/\f/g,'\\f').replace(/\r/g,'\\r').replace(/\t/g,'\\t').replace(/\v/g,'\\v').replace(/\0/g,'\\0').replace(/\'/g,'\\\'').replace(/\"/g,'\\\"')
echo text
enter q as '+text+'
snap page
```

**Comment by ccman32** [comment]
Hi @kensoh 
thank you for your quick response and suggestions.
I'm dynamically generating a script for tagui from within a C# application thus I tried to fix the problem with this C# code:
`passwordTextBox.Text.Replace("\\", "\\\\")`
The result of that expression will then be used in the tagui script.
So far that seems to work but I also noticed another issue:
When the password contains german umlauts like ä, ö or ü and I start tagui with the "firefox" argument, I get the following error:

> Script Error: Component returned failure code: 0x8050000e (NS_ERROR_ILLEGAL_INPUT) [nsIConverterInpu
> tStream.readString]
>        Stack:
>          -> resource://slimerjs/slUtils.jsm: 171 (in function readSyncStringFromFile)
>          -> resource://slimerjs/slimer-sdk/phantom.jsm: 173 (in function injectJs)
>          -> file:///C:/Users/<censored>/Desktop/tagui/src/casperjs/bin/bootstrap.js: 438
>          -> file:///C:/Users/<censored>/Desktop/tagui/src/casperjs/bin/bootstrap.js: 92

When not using the "firefox" argument, I do not get the error but the characters still seem to be handled incorrectly (in debug outputs for example I see "┐¢" instead of ö or sometimes also other symbols.
Is there a way to support these characters or is that not possible?

**Comment by kensoh** [comment]
Hi @ccman32 I can't replicate that, not sure what could be the issue. The error may have already happened in your C# program before the string is passed to TagUI. When I run below automation flow in default mode and in firefox mode, both creates the correct result showing the german characters.

Also, I'm running on macOS with Firefox 55.0.3 (64-bit). If below script works on macOS but fails on Windows, it could be CasperJS / PhantomJS / Firefox / Windows having an issue rendering correctly.

```
https://github.com/tebelorg
text = 'ä ö or ü'
echo 'ä ö or ü'
echo text
enter q as '+text+'
snap page
```

![snap1](https://user-images.githubusercontent.com/10379601/30248238-665eeaa2-9656-11e7-9c18-a94eb7ddcf11.png)

**Comment by ccman32** [comment]
I'm running it on Windows 7 64 bit. It does not happen with the C# application because I didn't use it when I noticed that problem. I just typed the characters manually in the script before executing it.

**Comment by kensoh** [comment]
```
https://github.com/tebelorg
text = 'ä ö or ü'
echo 'ä ö or ü'
echo text
enter q as '+text+'
snap page
```

I see.. Try copy the above flow script which works on macOS and save on your Windows (using the same edit you used to type manually). After that try opening the script to see how it looks? Then try executing it and opening the generated .js file to see the generated code block side by side with the flow script to see if the characters appear correctly in the generated script. It should be near the end of the generated .js file.

If the characters appear ok in source flow file but do not appear correctly in generated .js file, then something might have been not working from the point the PHP engine used by TagUI opens the file to read and then write to the generated .js file. If the generated .js the characters look ok, then it looks like issue happened when CasperJS / PhantomJS / SlimerJS tries to handle the characters. I did some search at their GitHub issues but was not able to find related issues.

**Comment by ccman32** [comment]
Opening the script again just shows exactly the same as I entered before saving it (obviously).
In the js file they also look the same. However, the output looks like this [http://i.imgur.com/osrHHWN.png](url)

Again when I run it with the firefox argument it gives this error:
[http://i.imgur.com/c0920Bh.png](url)

**Comment by kensoh** [comment]
I see.. Looks like there's nothing that can be done from TagUI side, since its job is to translate the automation flow file into a casperjs .js file and run it. I tried below minimum block of code on macOS (10.12) and Linux (Centos 6), both give correct output when run directly using casperjs filename.js. If this minimum block of code also cause error for you, you can try raising an issue at CasperJS github page - https://github.com/casperjs/casperjs/issues

```js
var casper = require('casper').create();

casper.start('https://github.com');

casper.then(function() {
text = 'ä ö or ü'
this.echo('ä ö or ü');
this.echo(text);
});

casper.run();
```

**summary of issue**
\ character in raw data treated as escape character. expected as execution engine is javascript. user changed source data \ to \\ to reflect backslash and works. another issue is some german characters appear wrong. found out issue don't happen on macos/linux but on windows 7. issue didn't happen during translation from tagui flow to casperjs file. but during execution casperjs somehow output incorrectly. recommended to raise issue at casperjs, no german umlauts issue found there.

**Comment by ccman32** [comment]
I just raised an issue at the CasperJS github (https://github.com/casperjs/casperjs/issues/1881) because that code also caused the same problem.

**Comment by kensoh** [comment]
Closing this issue for now as the German umlauts issue exists within CasperJS for your Windows 7 OS
