### ISSUE TITLE
file downloads using headless and visible Chrome

### ISSUE THREAD

**Issue by kensoh** [tebelorg/TagUI#65]
File downloading for visible Chrome can be done by normal webpage interaction. However, headless Chrome by default prevents that for security reason. [Chromium issue 696481](https://bugs.chromium.org/p/chromium/issues/detail?id=696481) has made good progress to support a new Chrome DevTools Protocol method [Page.setDownloadBehavior](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDownloadBehavior).

Chrome now allows overriding the default headless Chrome behavior of preventing downloads. This issue is raised to track the commits made to enable file downloads by default (to the same folder as flow file). A call is now made to enable file downloads to flow file folder, before an URL is accessed.

**Comment by kensoh** [comment]
closing issue, commit made to master and tested with [sample flow 3_github](https://github.com/tebelorg/TagUI/blob/master/src/samples/3_github)

**Comment by v-akos** [comment]
It seems that the method Page.setDownloadBehavior stopped woking with Chrome v71. You can read the same at the Chromium issue mentioned above.
