### ISSUE TITLE
Capture Screenshot as Mobile

### ISSUE THREAD

**Issue by lyonz** [tebelorg/TagUI#70]
Dear TagUI,
I just want to say thanks for your lovely tool!

How would I be able to capture the screen shot as mobile?

**Comment by kensoh** [comment]
Thanks @lyonz! This is not supported but you can try editing browser display size in tagui_config.txt. It may work on some websites that check the browser resolution to decide which version to show. Another more troublesome way is to experiment with setting browser user agent, but it is not fool-proof either.

**sample flow - `mobile`**
```
https://www.nrdc.org
snap page
```

**output of - `tagui mobile`**
**(desktop vs mobile)**

![screen shot 2017-11-29 at 4 06 10 am](https://user-images.githubusercontent.com/10379601/33341727-d1892250-d4ba-11e7-8d80-a79dee0240b4.png)
