### ISSUE TITLE
MSVCR110.dll is missing from your computer

### ISSUE THREAD

**Issue by kensoh** [tebelorg/TagUI#71]
Raising issue from feedback by Daniel from LifeCycle Solutions who is trying out TagUI. Thanks Dan!

---

I got an error from php.exe “The program can't start because MSVCR110.dll is missing from your computer.”  I googled and found this [related issue](https://serverfault.com/questions/517694/cant-start-php-cgi-exe-msvcr110-dll-is-missing).

I was able to fix by installing 32bit MSVCR110.dll: https://www.microsoft.com/en-us/download/confirmation.aspx?id=30679

Anyway, I thought I’d mention in case you want to note in your setup instructions, or handle somehow in the app.  I’m on Win10.  I would have expected this to be on there already, but maybe something to do w 32bit vs 64bit.

**Comment by kensoh** [comment]
**Fix that worked for Daniel is installing from Microsoft website - Visual C++ Redistributable for Visual Studio 2012 Update 4 - https://www.microsoft.com/en-us/download/details.aspx?id=30679**

It looks like some Windows systems may not have a common system file MSVCR110.dll that is used by PHP 32-bit version - https://github.com/tebelorg/TagUI/issues/69#issuecomment-343883204 . More details specific to [PHP and MSVCR110.dll](https://stackoverflow.com/questions/21397073/msvcr110-dll-is-missing-from-computer-error-while-installing-php).

---

Downloading automatically for user may not be a good idea, or detecting if the file is missing may not be robust. Going to put a note in readme for Windows download section, so that users who experience this can download from Microsoft website.

**Comment by kensoh** [comment]
Added this note prominently in the setup section where users download TagUI for Windows -

On some Windows computers, if you see 'MSVCR110.dll is missing' error, install [this from Microsoft website](https://www.microsoft.com/en-us/download/details.aspx?id=30679) - this file is required to run the PHP engine.

**Comment by kensoh** [comment]
Above commit adds a note to as Windows users to download the x86 (32-bit) version, this is because even if they are running 64-bit computers, the packaged PHP is still a 32-bit version for wider compatibility. Choosing the 64-bit version will still result in the error message. This note addresses that.

**Comment by sas-learn13** [comment]
Thank you! It did work...
