### ISSUE TITLE
grep and cut not available when running chrome from Windows

### ISSUE THREAD

**Issue by danroot** [tebelorg/TagUI#72]
Running a command like:
```
erina download my bank statement using chrome
```
fails on Windows machines with an error like "grep is not recognized as an internal or external command".  Installing grep results in a similar error for the 'cut' command.

One workaround is to install [grep ](http://gnuwin32.sourceforge.net/packages/grep.htm) and [coreutils ](http://gnuwin32.sourceforge.net/packages/coreutils.htm) for windows.
Alternatively, you can install the [chocolatey package manager](https://chocolatey.org/), then run the following:
```
choco install gnuwin32-coreutils.install -y
choco install gnuwin32-grep.install -y
```

After installing those, add C:\Program Files (x86)\GnuWin32\bin to PATH , restart your commandline, and the "using chrome" feature will work.

Alternatively, depending on licensing, etc the necessary commands could be included in the TagUI package, or the app changed to no longer need them.

**Comment by kensoh** [comment]
Hi @danroot thanks for raising this, appreciate it!

Can you try if this packaged installation for Windows works for you now?
https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI_Windows.zip

I was using a temporary Windows machine and somehow these files were missing before zipping. Have updated the Windows download zip file to contain the grep.exe and cut.exe commands.

**Comment by kensoh** [comment]
Have just borrowed a Windows laptop and verified that the Windows download zip works now.

Keeping this open for some time in case any other users ran into this earlier. Thanks Dan!
