### ISSUE TITLE
Tagui recording issue

### ISSUE THREAD

**Issue by vasanthaiwan** [tebelorg/TagUI#73]
I am trying to record the desktop/browser action using the TAGUI setup which was shared. but i am not able to auto record the actions performed by the User.
Kindly suggest me is that auto  recording of the Desktop/Browser is possible using TAGUI for Windows.

**Comment by kensoh** [comment]
Hi @vasanthaiwan, you may have missed the [Chrome extension section in readme](https://github.com/tebelorg/TagUI#chrome-extension). To record user actions on web browser, you'll need to install [TagUI Chrome extension](https://chrome.google.com/webstore/detail/tagui-web-automation/egdllmehgfgjebhlkjmcnhiocfcidnjk?hl=en) from Chrome web store.

The readme link above has more details on usage and limitations. If you want to record desktop actions, I recommend checking out [WorkFusion](https://www.workfusion.com/) or [UiPath](https://www.uipath.com/) - they are commercial RPA apps with recording functions.
