### ISSUE TITLE
Schedule tasks when new email arrives 

### ISSUE THREAD

**Issue by saniko** [tebelorg/TagUI#74]
Hello,
Is this possible?
Can I monitor email (such as gmail for instance) for new incoming email and trigger a sequence of tasks ?

**Comment by kensoh** [comment]
This should be possible, but done in the foreground on a real browser (Chrome) by running tagui with chrome option. Gmail will probably have security features to prevent logging in using the default PhantomJS invisible browser.

You can try writing the script to check for new emails, click on them, grab the contents to filter for keywords, then take actions on other tasks. I think there are many different type of scenarios so there are many ways to implement.
