### ISSUE TITLE
Running issue on Windows - System.Array.Empty()

### ISSUE THREAD

**Issue by kensoh** [tebelorg/TagUI#75]
**Raising an issue emailed to me as it might be relevant to other users.**

---

Hi Ken,

It's Akos from Budapest. :)

I have to implement my automation to Windows, because my users use Windows. This was the first time I tried to run any automation, and so far I've tried only on one machine.

However I have an error message rigth at the start in cmd:
C:\Users\varadia\Desktop\TagUI_Windows\tagui\src>tagui test.txt

Unhandled Exception: System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at casperjs.Main(String[] args)

I hope you have some suggestions because I have no idea.

Thanks for your help again!

Regards,
Akos

**Comment by kensoh** [comment]
Hi Akos, I missed Budapest and you all at Impact Hub! I wonder when I can visit your country again and other countries eastern part of Europe.

I have not heard of this issue happening to other Windows users. Can you try running the command tagui samples\1_yahoo to see what happens? I assume you download from the Windows packaged installation from TagUI readme page. I also assume you run directly in normal Windows command prompt and not Linux-shells on Windows.

**Comment by v-akos** [comment]
Hi Ken, Thanks for your reply! I've tried on a different Windows machine, but got the same message and result. Also tried your command, but the result is the same. Also found that casperjs.exe stopped.

Yes, I've used the Windows packed installation, and run directly in Windows' cmd.

It's a Windows 8.1 64 bites system, I guess with nothing special settings or installations.

Please let me know if there are any additional detail I could provide you!
And thanks for your help in advance!

**Comment by kensoh** [comment]
I'm afraid I can't help much as I can't replicate on my Windows 10. Searching the net shows possible cause from .NET framework.

https://stackoverflow.com/questions/31253747/method-not-found-0-system-array-empty-asapp-bundleconfig-registerbundl

If that's the cause, downloading a newer version of .NET framework may help -
https://www.microsoft.com/net/download/dotnet-framework-runtime

**Comment by v-akos** [comment]
I had the chance to try to update .Net framework on that Windows machine.
And I can tell you that it has solved all my problems! Now tagUI works like a scharm on that Win 8.1!

Thanks for your support, Ken!

**Comment by kensoh** [comment]
You're welcome Akos, glad to be of help! Thanks for raising this issue 😄
